<?php

namespace Kibatic\UX\Controller;

use Symfony\Component\Form\FormInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\HttpFoundation\Response;

class AbstractController extends \Symfony\Bundle\FrameworkBundle\Controller\AbstractController
{
    public function __construct(protected RequestStack $requestStack)
{
}
    public function createForm(string $type, mixed $data = null, array $options = [], bool $autoAction = true): FormInterface
    {
        if ($autoAction) {
            $options['action'] = $options['action'] ?? $this->requestStack->getCurrentRequest()->getUri();
        }

        return parent::createForm($type, $data, $options); // TODO: Change the autogenerated stub
    }
}
