services:
  _defaults:
    autowire: true
    autoconfigure: true

  Kibatic\UX\Twig\AppExtension:
    public: true
    tags:
      - { name: twig.extension }

  Kibatic\UX\Maker\MakeCrud:
    arguments:
      $doctrineHelper: '@maker.doctrine_helper'
      $formTypeRenderer: '@maker.renderer.form_type_renderer'
    tags:
      - { name: maker.command }
